name: testing

on:
  push:
    branches: [dev]
  pull_request:
    branches: [dev]

jobs:
  testing:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install Dependencies
        run: 'composer install --prefer-dist --no-progress --no-suggest'
      - name: Run Tests
        run: 'composer test-coverage'
      - name: Upload Codecov
        uses: codecov/codecov-action@v1.2.1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          file: ./coverage.xml
